# Generated by Django 4.0.6 on 2022-11-08 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_status',
            new_name='status',
        ),
    ]
