# Generated by Django 4.0.6 on 2022-11-09 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0002_rename_campaign_code_campaign_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='campaign_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='GM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_gm', to=settings.AUTH_USER_MODEL),
        ),
    ]
