# Generated by Django 4.0.6 on 2022-12-02 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0003_campaign_players_alter_campaign_gm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='GM',
            new_name='gm',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(blank=True, help_text='\n            For private campaigns, selected players will be able to join the campaign without having to enter\n            in the campaign code.\n            If you know the usernames of players who will be joining the campaign, \n            search for them here. (This will only work if they already have an account on this site).', related_name='campaign_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theseeker',
            name='major_arcana_unlocking',
            field=models.TextField(null=True, verbose_name="\n            You've begun to unlock the mysteries of your major arcanum.\n            When and how did that happen?\n            "),
        ),
    ]
