# Generated by Django 4.0.6 on 2022-12-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_rename_gm_campaign_gm_alter_campaign_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='private',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
