# Generated by Django 4.0.6 on 2022-12-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_remove_campaign_private_alter_campaign_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialpossessionextras',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
