# Generated by Django 4.0.6 on 2022-12-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_alter_appearanceattribute_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moves',
            options={'ordering': ['name']},
        ),
    ]
