# Generated by Django 4.0.6 on 2022-12-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_alter_moves_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
