# Generated by Django 4.0.6 on 2022-12-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_alter_moves_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_hp', models.IntegerField(default=6)),
                ('crew_armor', models.IntegerField(default=0)),
                ('crew_damage', models.CharField(choices=[('D4', 'D4'), ('D6', 'D6'), ('D8', 'D8'), ('D10', 'D10'), ('D12', 'D12'), ('D20', 'D20')], default='D6', max_length=10)),
                ('crew_instinct', models.CharField(choices=[('To bicker, infight, and hold grudges', 'To bicker, infight, and hold grudges'), ('To hew to tradition and superstition', 'To hew to tradition and superstition'), ('To indulge their baser instincts', 'To indulge their baser instincts'), ('To lord over others', 'To lord over others'), ('To take needless risks', 'To take needless risks'), ('To take things too far', 'To take things too far')], max_length=150)),
                ('crew_cost', models.CharField(choices=[('Merry-making, as a group', 'Merry-making, as a group'), ('Public recognition and respect, honor', 'Public recognition and respect, honor'), ('Risks taken, by you, to help them', 'Risks taken, by you, to help them'), ('Victories won against worthy foes', 'Victories won against worthy foes'), ('Wealth gained for themselves or Stonetop', 'Wealth gained for themselves or Stonetop')], max_length=150)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.character')),
                ('crew_tags', models.ManyToManyField(to='campaign.tags')),
                ('group_items', models.ManyToManyField(blank=True, to='campaign.iteminstance')),
                ('group_small_items', models.ManyToManyField(blank=True, to='campaign.smalliteminstance')),
                ('individuals', models.ManyToManyField(blank=True, to='campaign.followerinstance')),
            ],
        ),
    ]
