# Generated by Django 4.0.6 on 2023-01-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_crew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minorarcanum',
            options={'ordering': ['name']},
        ),
    ]
