# Generated by Django 4.0.6 on 2023-01-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_alter_minorarcanum_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorarcanum',
            options={'ordering': ['name']},
        ),
    ]
