# Generated by Django 4.0.6 on 2023-01-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_alter_majorarcanum_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='background',
            name='description2',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='description3',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
