# Generated by Django 4.0.6 on 2023-01-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_alter_background_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('Strength', 'Strength'), ('Dexterity', 'Dexterity'), ('Intelligence', 'Intelligence'), ('Wisdom', 'Wisdom'), ('Constitution', 'Constitution'), ('Charisma', 'Charisma')], max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='moverequirements',
            name='stat_restricted',
            field=models.ForeignKey(blank=True, help_text='Is there a stat requirement for this move?', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.statrequirement'),
        ),
    ]
