# Generated by Django 4.0.6 on 2023-02-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_statrequirement_moverequirements_stat_restricted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterclass',
            options={'ordering': ['class_name']},
        ),
        migrations.AlterField(
            model_name='arcanamoves',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
